name: Iniciar Curso

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # create first issue
      - name: Create First Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Configuração de Ambiente
          content-filepath: .github/content/issues/01-environment.md
            
